tasks:
  #aliyunpan_checkin:
  #  name: "阿里云盘签到"
  #  app: "阿里云盘"
  #  steps:
  #    - name: "Open folder"
  #      description: "Tap the Cloud folder on home screen"
  #    - name: "Open app"
  #      description: "Tap the 阿里云盘 icon"  
  #    - name: "Start check-in"
  #      description: "Tap the button that starts the daily check session"
  #    - name: "Complete check-in"
  #      description: "Tap the 领取 button at top-left region that completes the daily check session, if there is no 领取 button, see if there is a 明日可领取 button means you enter next step"
  #    - name: "Check result"
  #      description: "Check the 明日可领取 button means check-in success"
  #    - name: "Finish"
  #      description: "Returned to home, call task_complete"
  #taobao_checkin:
  #  name: "淘宝领取淘金币" 
  #  app: "淘宝"
  #  steps:
  #    - name: "Open app"
  #      description: "Find and tap the 淘宝 app icon on home screen"
  #    - name: "Start check-in"
  #      description: "Tap the button that starts the daily check session"
  #    - name: "Open sub page"
  #      description: "Find and tap the 领淘金币 icon to enter sub page"
  #    - name: "Complete check-in"
  #      description: "Tap the 点击签到 button at top-left region that completes the daily check session, if there is no 点击签到 button, see if there is a 赚更多金币 button means you enter next step"
  #    - name: "Check result"
  #      description: "Check the 赚更多金币 button means check-in success"
  #    - name: "Finish"
  #      description: "Returned to app home, call task_complete"
  clash_open:
    name: "打开Clash proxy" 
    app: "Clash"
    steps:
      - name: "slide screen"
        description: "Slide left on home screen"
      - name: "Open app"
        description: "Tap the Clash icon button, if not, return to home screen, step back to prior step"
      - name: "Open proxy"
        description: "Find and tap the 点此启动 button, if there is no 点此启动 button, see if there is a 运行中 button means you enter next step"
      - name: "Check result"
        description: "Check the 运行中 button means open-proxy success"
      - name: "Finish"
        description: "Returned to app home, call task_complete"
  clash_close:
    name: "关闭Clash proxy" 
    app: "Clash"
    steps:
      - name: "slide screen"
        description: "Slide left on home screen"
      - name: "Open app"
        description: "Tap the Clash icon button, if not, return to home screen, step back to prior step"
      - name: "Close proxy"
        description: "Find and tap the 运行中 button, if there is no 运行中 button, see if there is a 已停止 button means you enter next step"
      - name: "Check result"
        description: "Check the 已停止 button means close-proxy success"
      - name: "Finish"
        description: "Returned to app home, call task_complete"