tasks:
  aliyunpan_checkin:
    name: "阿里云盘签到"
    app: "阿里云盘"
    steps:
      - name: "打开文件夹"
        description: "点击主屏幕上的 Cloud 文件夹"
      - name: "打开应用"
        description: "进入文件夹，点击阿里云盘图标"
      - name: "开始签到"
        description: "点击开始每日签到的按钮"
      - name: "完成签到"
        description: "点击左上角的领取按钮完成每日签到，如果没有领取按钮，查看是否有明日可领取按钮，如果有则表示进入下一步"
      - name: "检查结果"
        description: "检查明日可领取按钮表示签到成功"
      - name: "完成"
        description: "返回主屏幕，调用完成"
  taobao_checkin:
    name: "淘宝领取淘金币"
    app: "淘宝"
    steps:
      - name: "打开应用"
        description: "找到并点击主屏幕上的淘宝应用图标"
      - name: "开始签到"
        description: "点击开始每日签到的按钮"
      - name: "打开子页面"
        description: "找到并点击领淘金币图标进入子页面"
      - name: "完成签到"
        description: "点击左上角的点击签到按钮完成每日签到，如果没有点击签到按钮，查看是否有赚更多金币按钮，如果有则表示进入下一步"
      - name: "检查结果"
        description: "检查赚更多金币按钮表示签到成功"
      - name: "完成"
        description: "返回应用主页，调用完成"
  clash_open:
    name: "打开 Clash 代理"
    app: "Clash"
    steps:
      - name: "滑动屏幕"
        description: "往右滑动到第二个屏幕（手指从右往左滑）"
      - name: "打开应用"
        description: "点击 Clash 图标按钮，如果没有，返回主屏幕，然后回到上一步"
      - name: "启动代理"
        description: "找到并点击点此启动按钮，如果没有点此启动按钮，查看是否有运行中按钮，如果有则表示进入下一步"
      - name: "检查结果"
        description: "检查运行中按钮表示代理启动成功"
      - name: "完成"
        description: "返回主屏幕，调用完成"
  #clash_close:
  #  name: "关闭 Clash 代理"
  #  app: "Clash"
  #  steps:
  #    - name: "滑动屏幕"
  #      description: "往右滑动到第二个屏幕（手指从右往左滑）"
  #    - name: "打开应用"
  #      description: "点击 Clash 图标按钮，如果没有，返回主屏幕，然后回到上一步"
  #    - name: "关闭代理"
  #      description: "找到并点击运行中按钮，如果没有运行中按钮，查看是否有已停止按钮，如果有则表示进入下一步"
  #    - name: "检查结果"
  #      description: "检查已停止按钮表示代理关闭成功"
  #    - name: "完成"
  #      description: "返回主屏幕，调用完成"
  #open_clock:
  #  name: "打开闹钟"
  #  app: "时钟"
  #  steps:
  #    - name: "打开应用"
  #      description: "找到并点击主屏幕上的时钟应用图标"
  #    - name: "打开对话"
  #      description: "找到 6:50 闹钟栏，如果没有，往下滑动"
  #    - name: "点击开启"
  #      description: "找到并点击开启按钮"
  #    - name: "完成"
  #      description: "返回主屏幕，调用完成"
  #close_clock:
  #  name: "删除闹钟"
  #  app: "时钟"
  #  steps:
  #    - name: "打开应用"
  #      description: "找到并点击主屏幕上的时钟应用图标"
  #    - name: "找到闹钟栏"
  #      description: "找到 7:55 闹钟栏，如果没有，往下滑动"
  #    - name: "点击关闭"
  #      description: "点击进入闹钟详情页，点击删除闹钟， 再次点击删除按钮，则完成任务，进入下一步"
  #    - name: "完成"
  #      description: "返回主屏幕，调用完成"